### ISSUE TITLE
Errore Aggiunta Articoli a preventivi

### ISSUE THREAD

**Issue by leonardocalabretta** [devcode-it/openstamanager#1010]
## Comportamento richiesto
Durante la creazione di un preventivo vorrei inserire un Articolo ma in alto a sinistra compare il messaggio "Preventivo modificato correttamente" ma poi non succede nulla.

## Passi per riprodurre il comportamento

Creare un preventivo e provare ad aggiungere un articolo

Eventuali log relativi (cartella **logs/**):
{"url":"/editor.php?id_module=13&id_record=134","ip":"10.94.51.13","http_method":"GET","server":"xxx.xxxxx.xxx","referrer":"https://xxx.xxxxx.xxx/controller.php?id_module=13","uid":"8448b81"}
[2022-02-02 00:30:26] Logs.ERROR: Uncaught Exception TypeError: "ksort(): Argument #1 ($array) must be of type array, null given" at /var/www/html/modules/preventivi/plugins/preventivi.consuntivo.php line 280 {"exception":"[object] (TypeError(code: 0): ksort(): Argument #1 ($array) must be of type array, null given at /var/www/html/modules/preventivi/plugins/preventivi.consuntivo.php:280)"}
{"url":"/editor.php?id_module=13&id_record=134","ip":"10.94.51.13","http_method":"POST","server":"xxx.xxxxx.xxx","referrer":"https://xxx.xxxxx.xxx/editor.php?id_module=13&id_record=134","uid":"e5356a7"}
[2022-02-02 00:30:26] Logs.ERROR: ksort(): Argument #1 ($array) must be of type array, null given {"code":0,"message":"ksort(): Argument #1 ($array) must be of type array, null given","file":"/var/www/html/modules/preventivi/plugins/preventivi.consuntivo.php","line":280,"trace":"#0 /var/www/html/modules/preventivi/plugins/preventivi.consuntivo.php(280): ksort(NULL)\n#1 /var/www/html/include/manager.php(36): include('/var/www/html/m...')\n#2 /var/www/html/editor.php(423): include('/var/www/html/i...')\n#3 {main}"}
{"url":"/editor.php?id_module=13&id_record=134","ip":"10.94.51.13","http_method":"POST","server":"xxx.xxxxx.xxx","referrer":"https://xxx.xxxxx.xxx/editor.php?id_module=13&id_record=134","uid":"e5356a7"}

## Contesto

Inserisci le informazioni riguardanti il tuo ambiente di esecuzione. Può essere utile per individuare problemi riproducibili solo con condizioni specifiche.

* Modulo: Preventivi
* Versione del progetto: 2.4.29
* Versione PHP: PHP 8.0.9 (cli) (built: Jul 30 2021 00:37:19) ( NTS )
* Tipo di server: Container docker Debian  con Apache 2.4.38
Girando dentro un container faccio fatica al volo a creare un nuovo container con php 7.4
Sulla 2.4.28 funzionava tutto correttamente. Stesse versioni di Apache e PHP

**Comment by leonardocalabretta** [comment]
Aggiungo che ho ricreato l'immagine con PHP7.4 e funziona tutto correttamente.

**Comment by loviuz** [comment]
Ciao @leonardocalabretta, è un problema legato a PHP 8 dalla 2.4.29. Stiamo vedendo di rilasciare una 2.4.30 con alcune modifiche in modo che la parte dei preventivi sia compatibile con PHP 8.
