### ISSUE TITLE
errore compilazione

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [devcode-it/openstamanager#1189]
Buongiorno,
sto cercando di ricompilare il sorgente con yarn run build-OSM

ma ricevo questo errore:
mi sapete indicare come posso risolvere?
grazie

Error: File not found with singular glob: D:/xampp/htdocs/xxx/node_modules/chart.js/dist/Chart.min.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (D:\xampp\htdocs\xxx\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:486:12)
    at Glob._finish (D:\xampp\htdocs\xxx\node_modules\glob\glob.js:194:8)
    at done (D:\xampp\htdocs\xxx\node_modules\glob\glob.js:179:14)
    at Glob._processSimple2 (D:\xampp\htdocs\xxx\node_modules\glob\glob.js:688:12)
    at D:\xampp\htdocs\xxx\node_modules\glob\glob.js:676:10
    at Glob._stat2 (D:\xampp\htdocs\xxx\node_modules\glob\glob.js:772:12)
    at lstatcb_ (D:\xampp\htdocs\xxx\node_modules\glob\glob.js:764:12)
[12:36:50] 'default' errored after 146 ms

**Comment by Pek5892** [comment]
Buongiorno @andreameneguzzoinfol,
potrebbe provare ad eseguire il comando ### yarn develop-OSM ?

**Comment by andreameneguzzoinfol** [comment]
Buongiorno, ho avuto errori poi di composer,risolti .
ora funziona grazie
