### ISSUE TITLE
Modifica riga articolo in preventivi ed attività da errore

### ISSUE THREAD

**Issue by bulleITA** [devcode-it/openstamanager#1489]
Se si prova a modificare una riga anche senza modificare nulla e premendo subito su salva da errore.
Ho provato anche nella demo.osmbusiness.it e fa uguale

Nel mio ambiente è riportato il seguente errore nei log

```
Logs.ERROR: Uncaught Exception BadMethodCallException: "Call to undefined method Modules\Interventi\Components\Articolo::setTranslation()" at /var/www/html/vendor/illuminate/support/Traits/ForwardsCalls.php line 71 {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Modules\\Interventi\\Components\\Articolo::setTranslation() at /var/www/html/vendor/illuminate/support/Traits/ForwardsCalls.php:71)"}
{"url":"/actions.php","ip":"10.0.0.128","http_method":"POST","server":"10.0.0.2","referrer":"http://10.0.0.2/editor.php?id_module=3&id_record=354","uid":"85aa280"} 
```

```
[2024-08-16 12:39:13] Logs.ERROR: Call to undefined method Modules\Interventi\Components\Articolo::setTranslation() {"code":0,"message":"Call to undefined method Modules\\Interventi\\Components\\Articolo::setTranslation()","file":"/var/www/html/vendor/illuminate/support/Traits/ForwardsCalls.php","line":71,"trace":"#0 /var/www/html/vendor/illuminate/support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException()\n#1 /var/www/html/vendor/illuminate/database/Eloquent/Model.php(2132): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()\n#2 /var/www/html/modules/interventi/actions.php(524): Illuminate\\Database\\Eloquent\\Model->__call()\n#3 /var/www/html/actions.php(489): include('...')\n#4 {main}"}
{"url":"/actions.php","ip":"10.0.0.128","http_method":"POST","server":"10.0.0.2","referrer":"http://10.0.0.2/editor.php?id_module=3&id_record=354","uid":"85aa280"}
``` 

* Versione del progetto: 2.5.3
* Versione PHP: 8.3.10
* Tipo di server: Apache2

**Comment by Pek5892** [comment]
Risolto con commit https://github.com/devcode-it/openstamanager/commit/b82efb339f8df5da4f2279e25d72904778d2a8d3
