### ISSUE TITLE
Problemi con la ricerca dei record (Fatture di vendita)

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#554]
## Comportamento attuale

Alcune volte la tabella delle fatture di vendita è vuota e viene mostrato sotto la tabella e sopra i tasti Seleziona tutto e Deseleziona tutto:
`Vista da 1 a 2 di 2 elementi (filtrati da 0 elementi totali)`
Sembra che sia impostato un filtro...

## Contesto

* Modulo: Fatture di vendita
* Versione del progetto: 2.4.8
* Versione PHP: 7.0
* Tipo di server: Apache

**Comment by Dasc3er** [comment]
Potresti controllare se ci sono dei filtri abilitati per il gruppo utente in questione? 
Ed eventualmente quale query viene eseguita secondo il modulo Viste...

**Comment by maicol07** [comment]
L'utente è un amministratore.
Nel modulo viste ci sono due filtri con lo stesso nome (Mostra ai clienti solo le proprie fatture) e uno è attivato mentre l'altro è disattivato.
```

SELECT IF((SELECT COUNT(t.numero_esterno) FROM co_documenti AS t WHERE t.numero_esterno = co_documenti.numero_esterno AND t.numero_esterno != '' AND t.id_segment = co_documenti.id_segment AND idtipodocumento IN (SELECT id FROM co_tipidocumento WHERE dir = 'entrata') AND t.data >= '2019-01-01' AND t.data <= '2019-12-31' AND YEAR(t.data) = YEAR(co_documenti.data) ) > 1, 'red', '') AS '_bg_', co_documenti.id AS 'id', idanagrafica AS 'idanagrafica', data AS 'Data', co_tipidocumento.descrizione AS 'Tipo', IF(numero_esterno='', numero, numero_esterno) AS 'Numero', (SELECT ragione_sociale FROM an_anagrafiche WHERE idanagrafica=co_documenti.idanagrafica) AS 'Ragione sociale', note_aggiuntive AS 'Note', (SELECT SUM(subtotale - sconto + rivalsainps - ritenutaacconto) FROM co_righe_documenti WHERE co_righe_documenti.iddocumento=co_documenti.id GROUP BY iddocumento) + bollo + iva_rivalsainps AS 'Totale netto', (SELECT SUM(subtotale - (prezzo_unitario_acquisto * qta)) FROM co_righe_documenti WHERE co_righe_documenti.iddocumento=co_documenti.id GROUP BY iddocumento) AS 'Guadagno', (SELECT SUM(iva) FROM co_righe_documenti WHERE co_righe_documenti.iddocumento=co_documenti.id GROUP BY iddocumento) AS 'Totale IVA', (SELECT SUM(subtotale - sconto + iva + rivalsainps - ritenutaacconto) FROM co_righe_documenti WHERE co_righe_documenti.iddocumento=co_documenti.id GROUP BY iddocumento) + bollo + iva_rivalsainps AS 'Totale', (SELECT icona FROM co_statidocumento WHERE id=idstatodocumento) AS 'icon_Stato', (SELECT scadenza FROM co_scadenziario WHERE iddocumento=co_documenti.id) AS 'Scadenza', IF((SELECT COUNT(1) FROM co_movimenti WHERE iddocumento=co_documenti.id AND primanota=1)=0, 'fa fa-times text-danger', 'fa fa-check text-success') AS 'icon_Prima nota', (SELECT descrizione FROM co_statidocumento WHERE id=idstatodocumento) AS 'icon_title_Stato', dir AS 'dir', (SELECT `icon` FROM `fe_stati_documento` WHERE `codice` = `codice_stato_fe`) AS 'icon_FE', (SELECT `descrizione` FROM `fe_stati_documento` WHERE `codice` = `codice_stato_fe`) AS 'icon_title_FE', (IF((SELECT MAX(zz_operations.created_at) FROM zz_operations WHERE zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = 'Fatture di vendita') AND op = 'send' AND id_record = co_documenti.id ORDER BY zz_operations.created_at) != "", (SELECT MAX(zz_operations.created_at) FROM zz_operations WHERE zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = 'Fatture di vendita') AND op = 'send' AND id_record = co_documenti.id ORDER BY zz_operations.created_at), (SELECT MAX(zz_operations.created_at) FROM zz_operations WHERE zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = 'Fatture di vendita') AND op = 'generate' AND id_record = co_documenti.id ORDER BY zz_operations.created_at))) AS 'Data invio FE', IF((SELECT GROUP_CONCAT(DISTINCT `name` SEPARATOR ' ') FROM zz_operations INNER JOIN zz_emails ON zz_operations.id_email = zz_emails.id WHERE zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = 'Fatture di vendita') AND op = 'send-email' AND id_record = co_documenti.id ORDER BY zz_operations.created_at DESC LIMIT 1) IS NOT NULL, 'fa fa-envelope text-success', '') AS 'icon_Inviata', (SELECT GROUP_CONCAT(DISTINCT `name` SEPARATOR ' ') FROM zz_operations INNER JOIN zz_emails ON zz_operations.id_email = zz_emails.id WHERE zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = 'Fatture di vendita') AND op = 'send-email' AND id_record = co_documenti.id ORDER BY zz_operations.created_at DESC LIMIT 1) AS 'icon_title_Inviata', IF((SELECT COUNT(1) FROM co_movimenti WHERE iddocumento=co_documenti.id AND primanota=1)=0, 'No', 'Sì') AS 'icon_title_Prima nota', (SELECT MAX(zz_operations.created_at) FROM zz_operations INNER JOIN zz_emails ON zz_operations.id_email = zz_emails.id WHERE zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = 'Fatture di vendita') AND op = 'send-email' AND id_record = co_documenti.id ORDER BY zz_operations.created_at) AS 'Data invio', (IF((SELECT COUNT(1) FROM zz_operations WHERE zz_operations.op = 'export-xml-bulk' AND zz_operations.id_record = co_documenti.id AND zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = 'Fatture di vendita') ORDER BY zz_operations.created_at DESC LIMIT 1) != 0, 'fa fa-check text-success', 'fa fa-times text-danger')) AS 'icon_Commerc.', (IF((SELECT COUNT(1) FROM zz_operations WHERE zz_operations.op = 'export-xml-bulk' AND zz_operations.id_record = co_documenti.id AND zz_operations.id_module = (SELECT id FROM zz_modules WHERE `name` = 'Fatture di vendita') ORDER BY zz_operations.created_at DESC LIMIT 1) != 0, 'Sì', 'No')) AS 'icon_title_Commerc.' FROM `co_documenti` INNER JOIN `co_tipidocumento` ON `co_documenti`.`idtipodocumento` = `co_tipidocumento`.`id` WHERE 1=1 AND `dir` = 'entrata' AND `data` >= '2019-01-01' AND `data` <= '2019-12-31' HAVING 2=2 ORDER BY `numero_esterno` ASC, CAST(numero_esterno AS UNSIGNED) DESC
```

**Comment by Dasc3er** [comment]
Putroppo in questo caso non siamo riusciti a riscontrare il problema...
Se continua a presentarsi, segnalalo qui nuovamente e proveremo a replicarlo di nuovo 😞

**Comment by maicol07** [comment]
@Dasc3er l'errore si è ripresentato.
Query risultante: https://pastebin.com/5YnR9VWj
I log riportano questo errore:
```
[2019-07-31 11:04:26] Logs.ERROR: Call to a member function calcola() on null {"code":0,"message":"Call to a member function calcola() on null","file":"/home/mhd-01/www.battistini-impianti.it/htdocs/amministrazione/modules/fatture/src/Fattura.php","line":348,"trace":"#0 /home/mhd-01/www.battistini-impianti.it/htdocs/amministrazione/modules/fatture/src/Fattura.php(400): Modules\\Fatture\\Fattura->registraScadenzeTradizionali(false)\n#1 /home/mhd-01/www.battistini-impianti.it/htdocs/amministrazione/modules/fatture/modutil.php(111): Modules\\Fatture\\Fattura->registraScadenze(false)\n#2 /home/mhd-01/www.battistini-impianti.it/htdocs/amministrazione/modules/fatture/actions.php(116): aggiungi_scadenza('270')\n#3 /home/mhd-01/www.battistini-impianti.it/htdocs/amministrazione/actions.php(240): include('/home/mhd-01/ww...')\n#4 {main}"}
{"url":"/amministrazione/actions.php","ip":"151.42.237.103","http_method":"POST","server":"amministrazione.battistini-impianti.it","referrer":"http://amministrazione.battistini-impianti.it/amministrazione/editor.php?id_module=14&id_record=270","unique_id":"XUFZmtlAw6QAACPMtXYAAADF","uid":"862c7e9"p 

```

**Comment by Dasc3er** [comment]
@maicol07 Credo il problema sia causato dalle componenti che sono state aggiunte alla query originale...

**Comment by maicol07** [comment]
Ho provato anche con la query originale senza nessun risultato...

**Comment by maicol07** [comment]
Il problema si ripresenta...

**Comment by maicol07** [comment]
@Dasc3er ho provato ad eseguire la query risultante all'interno di PHPMyAdmin e sembra che dia come risultato il seguente errore:
`#3024 - Query execution was interrupted, maximum statement execution time exceeded`
Ho contattato il mio hosting per chiedere di aumentare il tempo di timeout
