### ISSUE TITLE
Crash database

### ISSUE THREAD

**Issue by algua1213** [devcode-it/openstamanager#720]
## Comportamento richiesto

Nel momento in cui all'interno del programma si va a modificare un contratto il db va in crash.

## Passi per riprodurre il comportamento

1.Creo nuovo contratto
2.Modifico lo stato
3.Non va più niente

Eventuale codice rilevante:
```php
Se serve, aggiungi qui il codice che vuoi farci testare
```

Eventuali log relativi (cartella **logs/**):
```
Se presenti, aggiungi qui i log relativi al malfunzionamento
```

## Contesto

Installato tutto con ultima versione di osm e xampp

**Comment by Dasc3er** [comment]
@algua1213 Per favore, includi maggiori informazioni tecniche. Se hai bisogno di un supporto così poco definito ti consiglio di utilizzare il forum.

Versione del gestionale? In che senso "non fa niente": schermata bianca, errore, ...? Ci sono dei log nella cartella logs/?

**Comment by algua1213** [comment]
Versione del gestionale 
![image](https://user-images.githubusercontent.com/23247554/71641914-7310e580-2ca3-11ea-84a1-44087474bbbc.png)
installato con xampp versione 3.2.4

Come scritto quando vado a inserire un nuovo contratto non riscontro errori, nel momento in cui vado a modificarlo, in particolare vado a modificarne lo stato

![image](https://user-images.githubusercontent.com/23247554/71641980-63de6780-2ca4-11ea-9c68-0493c9c3d3d0.png)

mi ritrovo con la pagina bianca
![image](https://user-images.githubusercontent.com/23247554/71641988-7b1d5500-2ca4-11ea-8e5d-617b31a763b3.png)

e db down

![image](https://user-images.githubusercontent.com/23247554/71641992-92f4d900-2ca4-11ea-8468-abc3d41c4498.png)


il log riporta quanto segue:
`[2020-01-01 14:38:52] Logs.ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" at C:\xampp\htdocs\gestionale\src\Database.php line 240 {"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at C:\\xampp\\htdocs\\gestionale\\src\\Database.php:240)"}
{"url":"/gestionale/editor.php?id_module=31&id_record=3","ip":"192.168.3.4","http_method":"POST","server":"192.168.3.5","referrer":"http://192.168.3.5/gestionale/editor.php?id_module=31&id_record=3","uid":"8e76a7f"} 
[2020-01-01 14:38:52] Logs.ERROR: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away {"code":"HY000","message":"SQLSTATE[HY000]: General error: 2006 MySQL server has gone away","file":"C:\\xampp\\htdocs\\gestionale\\src\\Database.php","line":240,"trace":"#0 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(240): PDOStatement->execute(Array)\n#1 C:\\xampp\\htdocs\\gestionale\\modules\\contratti\\actions.php(36): Database->fetchArray('SELECT (SELECT ...')\n#2 C:\\xampp\\htdocs\\gestionale\\actions.php(292): include('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\gestionale\\editor.php(32): include_once('C:\\\\xampp\\\\htdocs...')\n#4 {main}"}
{"url":"/gestionale/editor.php?id_module=31&id_record=3","ip":"192.168.3.4","http_method":"POST","server":"192.168.3.5","referrer":"http://192.168.3.5/gestionale/editor.php?id_module=31&id_record=3","uid":"8e76a7f"} 
[2020-01-01 14:38:57] Logs.ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione. " at C:\xampp\htdocs\gestionale\vendor\illuminate\database\Connectors\Connector.php line 68 {"exception":"[object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.\r\n at C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php:68)"}
{"url":"/gestionale/ajax.php?op=hook-lock&id=5","ip":"192.168.3.4","http_method":"GET","server":"192.168.3.5","referrer":"http://192.168.3.5/gestionale/controller.php?id_module=1","uid":"a08dca7"} 
[2020-01-01 14:38:57] Logs.ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione. " at C:\xampp\htdocs\gestionale\vendor\illuminate\database\Connectors\Connector.php line 68 {"exception":"[object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.\r\n at C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php:68)"}
{"url":"/gestionale/ajax.php?op=hook-lock&id=6","ip":"192.168.3.4","http_method":"GET","server":"192.168.3.5","referrer":"http://192.168.3.5/gestionale/controller.php?id_module=1","uid":"cd1b590"} 
[2020-01-01 14:38:57] Logs.ERROR: SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.  {"code":2002,"message":"SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.\r\n","file":"C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php(68): PDO->__construct('mysql:host=loca...', 'user', 'Password12', Array)\n#1 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=loca...', 'user', 'Password12', Array)\n#2 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=loca...', Array, Array)\n#3 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)\n#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()\n#5 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connection.php(883): call_user_func(Object(Closure))\n#6 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(134): Illuminate\\Database\\Connection->getPdo()\n#7 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(71): Database->getPDO()\n#8 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(114): Database->__construct('localhost', 'user', 'Password12', 'webiiilab')\n#9 C:\\xampp\\htdocs\\gestionale\\lib\\helpers.php(17): Database::getConnection()\n#10 C:\\xampp\\htdocs\\gestionale\\core.php(124): database()\n#11 C:\\xampp\\htdocs\\gestionale\\ajax.php(3): include_once('C:\\\\xampp\\\\htdocs...')\n#12 {main}"}
{"url":"/gestionale/ajax.php?op=hook-lock&id=5","ip":"192.168.3.4","http_method":"GET","server":"192.168.3.5","referrer":"http://192.168.3.5/gestionale/controller.php?id_module=1","uid":"a08dca7"} 
[2020-01-01 14:38:57] Logs.ERROR: SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.  {"code":2002,"message":"SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.\r\n","file":"C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php(68): PDO->__construct('mysql:host=loca...', 'user', 'Password12', Array)\n#1 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=loca...', 'user', 'Password12', Array)\n#2 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=loca...', Array, Array)\n#3 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)\n#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()\n#5 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connection.php(883): call_user_func(Object(Closure))\n#6 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(134): Illuminate\\Database\\Connection->getPdo()\n#7 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(71): Database->getPDO()\n#8 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(114): Database->__construct('localhost', 'user', 'Password12', 'webiiilab')\n#9 C:\\xampp\\htdocs\\gestionale\\lib\\helpers.php(17): Database::getConnection()\n#10 C:\\xampp\\htdocs\\gestionale\\core.php(124): database()\n#11 C:\\xampp\\htdocs\\gestionale\\ajax.php(3): include_once('C:\\\\xampp\\\\htdocs...')\n#12 {main}"}
{"url":"/gestionale/ajax.php?op=hook-lock&id=6","ip":"192.168.3.4","http_method":"GET","server":"192.168.3.5","referrer":"http://192.168.3.5/gestionale/controller.php?id_module=1","uid":"cd1b590"} 
[2020-01-01 14:39:06] Logs.ERROR: Uncaught Exception PDOException: "SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione. " at C:\xampp\htdocs\gestionale\vendor\illuminate\database\Connectors\Connector.php line 68 {"exception":"[object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.\r\n at C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php:68)"}
{"url":"/gestionale/ajax.php?op=hook-lock&id=5","ip":"192.168.3.4","http_method":"GET","server":"192.168.3.5","referrer":"http://192.168.3.5/gestionale/controller.php?id_module=1","uid":"430e6db"} 
[2020-01-01 14:39:06] Logs.ERROR: SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.  {"code":2002,"message":"SQLSTATE[HY000] [2002] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione.\r\n","file":"C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php","line":68,"trace":"#0 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php(68): PDO->__construct('mysql:host=loca...', 'user', 'Password12', Array)\n#1 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=loca...', 'user', 'Password12', Array)\n#2 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=loca...', Array, Array)\n#3 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connectors\\ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)\n#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()\n#5 C:\\xampp\\htdocs\\gestionale\\vendor\\illuminate\\database\\Connection.php(883): call_user_func(Object(Closure))\n#6 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(134): Illuminate\\Database\\Connection->getPdo()\n#7 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(71): Database->getPDO()\n#8 C:\\xampp\\htdocs\\gestionale\\src\\Database.php(114): Database->__construct('localhost', 'user', 'Password12', 'webiiilab')\n#9 C:\\xampp\\htdocs\\gestionale\\lib\\helpers.php(17): Database::getConnection()\n#10 C:\\xampp\\htdocs\\gestionale\\core.php(124): database()\n#11 C:\\xampp\\htdocs\\gestionale\\ajax.php(3): include_once('C:\\\\xampp\\\\htdocs...')\n#12 {main}"}
{"url":"/gestionale/ajax.php?op=hook-lock&id=5","ip":"192.168.3.4","http_method":"GET","server":"192.168.3.5","referrer":"http://192.168.3.5/gestionale/controller.php?id_module=1","uid":"430e6db"} 
`
vi possono servire altri dettagli?

Grazie.

**Comment by Dasc3er** [comment]
No, in questo caso hai inserito tutti i dettagli che sembrano di interesse...
Apparentemente MySQL viene spento da Wamp, riusciresti a fare test in un altro ambiente server? Il problema si verifica solo a seguito di questa azione particolare?

**Comment by algua1213** [comment]
Subito non riuscirei, al massimo potrei su un nas synology, potrebbe cambiar qualcosa? Se vi indico i log di mysql?

**Comment by Dasc3er** [comment]
Potrebbe essere utile, poiché a occhio dai log sembra che la causa del problema sia proprio wamp...

**Comment by algua1213** [comment]
eccolo di seguito:

200101 14:38:51 [ERROR] mysqld got exception 0xc0000005 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed, 
something is definitely wrong and this may fail.

Server version: 10.4.10-MariaDB
key_buffer_size=167772160
read_buffer_size=10485760
max_used_connections=9
max_threads=65537
thread_count=7
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 182337 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x20753fc4c88
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
mysqld.exe!?fix_fields@Item_field@@UEAA_NPEAVTHD@@PEAPEAVItem@@@Z()
mysqld.exe!?fix_fields@Item_func@@UEAA_NPEAVTHD@@PEAPEAVItem@@@Z()
mysqld.exe!?pushdown_from_having_into_where@st_select_lex@@QEAAPEAVItem@@PEAVTHD@@PEAV2@@Z()
mysqld.exe!?optimize_inner@JOIN@@QEAAHXZ()
mysqld.exe!?optimize@JOIN@@QEAAHXZ()
mysqld.exe!?optimize_unflattened_subqueries@st_select_lex@@QEAA_N_N@Z()
mysqld.exe!?optimize_stage2@JOIN@@QEAAHXZ()
mysqld.exe!?optimize_inner@JOIN@@QEAAHXZ()
mysqld.exe!?optimize@JOIN@@QEAAHXZ()
mysqld.exe!?mysql_select@@YA_NPEAVTHD@@PEAUTABLE_LIST@@IAEAV?$List@VItem@@@@PEAVItem@@IPEAUst_order@@434_KPEAVselect_result@@PEAVst_select_lex_unit@@PEAVst_select_lex@@@Z()
mysqld.exe!?handle_select@@YA_NPEAVTHD@@PEAULEX@@PEAVselect_result@@K@Z()
mysqld.exe!?execute_init_command@@YAXPEAVTHD@@PEAUst_mysql_lex_string@@PEAUst_mysql_rwlock@@@Z()
mysqld.exe!?mysql_execute_command@@YAHPEAVTHD@@@Z()
mysqld.exe!?execute@Prepared_statement@@AEAA_NPEAVString@@_N@Z()
mysqld.exe!?execute_loop@Prepared_statement@@QEAA_NPEAVString@@_NPEAE2@Z()
mysqld.exe!?mysql_sql_stmt_prepare@@YAXPEAVTHD@@@Z()
mysqld.exe!?mysqld_stmt_execute@@YAXPEAVTHD@@PEADI@Z()
mysqld.exe!?dispatch_command@@YA_NW4enum_server_command@@PEAVTHD@@PEADI_N3@Z()
mysqld.exe!?do_command@@YA_NPEAVTHD@@@Z()
mysqld.exe!?pool_of_threads_scheduler@@YAXPEAUscheduler_functions@@PEAKPEAI@Z()
mysqld.exe!?tp_callback@@YAXPEAUTP_connection@@@Z()
KERNEL32.DLL!ReadProcessMemory()
ntdll.dll!TpCallbackIndependent()
ntdll.dll!RtlInitializeResource()
KERNEL32.DLL!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x207537bf410): SELECT (SELECT SUM(subtotale) FROM co_righe_contratti GROUP BY idcontratto HAVING idcontratto=co_contratti.id) AS 'budget' FROM co_contratti WHERE id='3'
Connection ID (thread ID): 21763
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=on,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on,split_materialized=on,condition_pushdown_for_subquery=on,rowid_filter=on,condition_pushdown_from_having=on

The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.
Writing a core file at C:\xampp\mysql\data\
InnoDB: using atomic writes.
2020-01-01 14:42:26 0 [Note] InnoDB: Mutexes and rw_locks use Windows interlocked functions
2020-01-01 14:42:26 0 [Note] InnoDB: Uses event mutexes
2020-01-01 14:42:26 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-01-01 14:42:26 0 [Note] InnoDB: Number of pools: 1
2020-01-01 14:42:26 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-01-01 14:42:26 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2020-01-01 14:42:26 0 [Note] InnoDB: Completed initialization of buffer pool
2020-01-01 14:42:26 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=35678882
2020-01-01 14:42:26 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-01-01 14:42:26 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-01-01 14:42:26 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-01-01 14:42:26 0 [Note] InnoDB: Setting file 'C:\xampp\mysql\data\ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-01-01 14:42:26 0 [Note] InnoDB: File 'C:\xampp\mysql\data\ibtmp1' size is now 12 MB.
2020-01-01 14:42:26 0 [Note] InnoDB: Waiting for purge to start
2020-01-01 14:42:26 0 [Note] InnoDB: 10.4.10 started; log sequence number 35678891; transaction id 88634
2020-01-01 14:42:26 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-01-01 14:42:26 0 [Note] InnoDB: Loading buffer pool(s) from C:\xampp\mysql\data\ib_buffer_pool
2020-01-01 14:42:26 0 [Note] Server socket created on IP: '::'.
2020-01-01 14:42:26 0 [Note] Reading of all Master_info entries succeeded
2020-01-01 14:42:26 0 [Note] Added new Master_info '' to hash table
2020-01-01 14:42:26 0 [Note] C:\xampp\mysql\bin\mysqld.exe: ready for connections.
Version: '10.4.10-MariaDB'  socket: ''  port: 3306  mariadb.org binary distribution
2020-01-01 14:42:27 0 [Note] InnoDB: Buffer pool(s) load completed at 200101 14:42:27
2020-01-01 14:47:48 603 [Warning] Aborted connection 603 to db: 'webiiilab' user: 'user' host: 'localhost' (Got an error reading communication packets)
2020-01-01 14:47:48 604 [Warning] Aborted connection 604 to db: 'webiiilab' user: 'user' host: 'localhost' (Got an error reading communication packets)
2020-01-01 14:47:48 605 [Warning] Aborted connection 605 to db: 'webiiilab' user: 'user' host: 'localhost' (Got an error reading communication packets)
2020-01-01 14:47:48 606 [Warning] Aborted connection 606 to db: 'webiiilab' user: 'user' host: 'localhost' (Got an error reading communication packets)
2020-01-01 14:47:48 607 [Warning] Aborted connection 607 to db: 'webiiilab' user: 'user' host: 'localhost' (Got an error reading communication packets)

**Comment by Dasc3er** [comment]
L'unica soluzione che mi viene in mente è di provare appunto su un altro Server, e se il problema persiste provare s segnalare il malfunzionamento nella community MySQL per ottenere suggerimenti.
Questa è la prima volta che si verifica qualcosa del genere, quindi direi che la probabile causa è Wamp che ha installato "male" MySQL, e quindi direi di provare altrove. Se necessiti di una demo gratuita di 30 giorni, puoi richiederla attraverso il sito commerciale del gestionale www.openstamanager.com.

**Comment by algua1213** [comment]
Ok, grazie, tenterò sul nas ed eventualmente procederò con la demo.
