### ISSUE TITLE
Incompatibilità con PHP 8 (2.4.x)

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#918]
Magari è utile avere un issue in cui segnalare eventuali incompatibilità con PHP 8 per le versioni 2.4.x del progetto con eventuali soluzioni temporanee in attesa di un fix definitivo.

Bug presenti al momento:
- Errore all'apertura di ogni modulo che presenta una vista (riscontrato dalla v2.4.20): 
  ```
	  [2020-12-31 21:40:50] Logs.ERROR: NumberFormatter::format(): Argument #1 ($num) must be of type int|float, string given {"code":0,"message":"NumberFormatter::format(): Argument #1 ($num) must be of type int|float, string given","file":"/home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/Intl/Formatter.php","line":152,"trace":"#0 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/Intl/Formatter.php(152): NumberFormatter->format()\n#1 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/Intl/Formatter.php(217): Intl\\Formatter->formatNumber()\n#2 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/ajax_dataload.php(86): Intl\\Formatter->isStandardNumber()\n#3 {main}"}
	  {"url":"/ajax_dataload.php?id_module=37&id_plugin=&id_parent=&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=false&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=200&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1609447249998","ip":"192.168.1.1","http_method":"GET","server":"amministrazione.battistini-impianti.it","referrer":"https://amministrazione.battistini-impianti.it/controller.php?id_module=37","uid":"c36b756"} 
	```
	**Soluzione temporanea**: Effettuare un casting sul parametro della funzione format alla seguente riga:
	https://github.com/devcode-it/openstamanager/blob/9697b1bc2dd13b0756da6aad7a4c9d94178b5c22/src/Intl/Formatter.php#L151
- Errore su hook Ricevute (riscontrato dalla v2.4.20):
	```
	[2020-12-31 21:57:56] Logs.ERROR: Cannot access offset of type string on string {"code":0,"message":"Cannot access offset of type string on string","file":"/home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/Models/Upload.php","line":55,"trace":"#0 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/receiptFE/src/Ricevuta.php(177): Models\\Upload::build()\n#1 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/receiptFE/src/Ricevuta.php(229): Plugins\\ReceiptFE\\Ricevuta->saveAllegato()\n#2 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/receiptFE/src/Ricevuta.php(101): Plugins\\ReceiptFE\\Ricevuta->save()\n#3 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/receiptFE/src/ReceiptHook.php(77): Plugins\\ReceiptFE\\Ricevuta::process()\n#4 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/Hooks/Manager.php(75): Plugins\\ReceiptFE\\ReceiptHook->execute()\n#5 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/Models/Hook.php(64): Hooks\\Manager->manage()\n#6 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/ajax.php(139): Models\\Hook->execute()\n#7 {main}"}
	{"url":"/ajax.php?op=hook-execute&id=1&token=8wkubwn5vz7MJRxa","ip":"192.168.1.1","http_method":"GET","server":"amministrazione.battistini-impianti.it","referrer":"https://amministrazione.battistini-impianti.it/controller.php?id_module=14","uid":"40f5110"} 
	```
	**Soluzione temporanea**: Sostituire la riga seguente con la riga 80 dello stesso file (eliminare la riga 80 dopo la sostituzione):
	https://github.com/devcode-it/openstamanager/blob/9697b1bc2dd13b0756da6aad7a4c9d94178b5c22/src/Models/Upload.php#L55
- Errore durante importazione FE (riscontrato dalla v2.4.20):
	```
	[2021-01-04 10:58:35] Logs.ERROR: Cannot access offset of type string on string {"code":0,"message":"Cannot access offset of type string on string","file":"/home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/importFE/src/FatturaOrdinaria.php","line":90,"trace":"#0 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/importFE/generate.php(280): Plugins\\ImportFE\\FatturaOrdinaria->getRighe()\n#1 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/importFE/edit.php(26): include('...')\n#2 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/editor.php(247): include('...')\n#3 {main}"}
	{"url":"/editor.php?id_module=15&id_plugin=19&id_record=5&data_registrazione=2020-12-29&","ip":"151.34.196.155","http_method":"GET","server":"amministrazione.battistini-impianti.it","referrer":"https://amministrazione.battistini-impianti.it/controller.php?id_module=15","uid":"11d0971"} 
	```
	**Soluzione temporanea**: Il problema è causato dal fatto che l'array `$riepiloghi` non è un array di array ma un array semplice:
    ```
	array(5) { ["AliquotaIVA"]=> string(5) "22.00" ["ImponibileImporto"]=> string(5) "33.47" ["Imposta"]=> string(4) "7.36" ["EsigibilitaIVA"]=> string(1) "I" ["RiferimentoNormativo"]=> string(14) "22% - GENERICO" } 
	```
	Pertanto, è necessario effettuare un controllo sostitudendo:
	https://github.com/devcode-it/openstamanager/blob/bf8c108121396e837e84e2931cdc5663b02e1bad/plugins/importFE/src/FatturaOrdinaria.php#L87
	con:
	```php
	// Aggiunta degli arrotondamenti IVA come righe indipendenti
    $riepiloghi = $this->getBody()['DatiBeniServizi']['DatiRiepilogo'];
    if (!empty($riepiloghi['AliquotaIVA'])) {
        $riepiloghi = [$riepiloghi];
    }
    foreach ($riepiloghi as $riepilogo) {
	```
- Errore durante importazione FE (riscontrato dalla v2.4.20):
	```
	[2021-01-04 11:15:54] Logs.ERROR: Cannot access offset of type string on string {"code":0,"message":"Cannot access offset of type string on string","file":"/home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/importFE/generate.php","line":303,"trace":"#0 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/plugins/importFE/edit.php(26): include()\n#1 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/editor.php(247): include('...')\n#2 {main}"}
	{"url":"/editor.php?id_module=15&id_plugin=19&id_record=1&data_registrazione=2020-12-31&","ip":"151.34.196.155","http_method":"GET","server":"amministrazione.battistini-impianti.it","referrer":"https://amministrazione.battistini-impianti.it/controller.php?id_module=15","uid":"d3efbd5"} 
	```
	**Soluzione temporanea**: Il problema è causato dal fatto che l'array `$righe` non è un array di array ma un array semplice (la fattura contiene una sola riga).
	Pertanto, è necessario inserire un controllo alla riga 300:
	https://github.com/devcode-it/openstamanager/blob/bf8c108121396e837e84e2931cdc5663b02e1bad/plugins/importFE/generate.php#L300
	Codice controllo:
	```php
	if (isset($righe['NumeroLinea'])) {
        $righe = [$righe];
    }
	```

**Comment by maicol07** [comment]
Aggiornato primo post con nuovi errori
