### ISSUE TITLE
Errore SQL fattura collegata

### ISSUE THREAD

**Issue by maicol07** [devcode-it/openstamanager#936]
## Comportamento attuale
Impossibile selezionare una fattura collegata alla nota di credito in fase di import (errore sql nei log).

## Passi per riprodurre il comportamento
1. Importare una nota di credito

Eventuali log relativi (cartella **logs/**):
```
{"url":"/editor.php?id_module=15&id_plugin=19&id_record=1&data_registrazione=2021-01-25&","ip":"151.18.58.203","http_method":"GET","server":"amministrazione.battistini-impianti.it","referrer":"https://amministrazione.battistini-impianti.it/controller.php?id_module=15","uid":"a817b1b"} 
[2021-01-26 10:23:02] Logs.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE
            co_tipidocumento.dir = 'uscita' AND
            (co_documen...' at line 7 {"code":"42000","message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE
            co_tipidocumento.dir = 'uscita' AND
            (co_documen...' at line 7","file":"/home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/Database.php","line":257,"trace":"#0 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/Database.php(257): PDO->prepare()
#1 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/HTMLBuilder/Handler/SelectHandler.php(235): Database->fetchArray()
#2 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/HTMLBuilder/Handler/SelectHandler.php(90): HTMLBuilder\\Handler\\SelectHandler->selectQuery()
#3 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/HTMLBuilder/HTMLBuilder.php(352): HTMLBuilder\\Handler\\SelectHandler->handle()
#4 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/src/HTMLBuilder/HTMLBuilder.php(155): HTMLBuilder\\HTMLBuilder::generate()
#5 /home/battistini-impianti.it/amministrazione.battistini-impianti.it/lib/functions.php(232): HTMLBuilder\\HTMLBuilder::replace()
#6 [internal function]: translateTemplate()
#7 {main}"}
{"url":"/editor.php?id_module=15&id_plugin=19&id_record=1&data_registrazione=2021-01-25&","ip":"151.18.58.203","http_method":"POST","server":"amministrazione.battistini-impianti.it","referrer":"https://amministrazione.battistini-impianti.it/editor.php?id_module=15&id_plugin=19&id_record=1&data_registrazione=2021-01-25&","uid":"f49d7c4"} 
```

## Contesto
* Modulo: Fatture di acquisto
* Versione del progetto: 2.4.21
* Versione PHP: 7.4
* Tipo di server: OpenLiteSpeed

**Comment by Dasc3er** [comment]
@maicol07 Non sono riuscito a replicare il problema al momento (per assenza di fatture su cui testare il bug).
Credo però che sia dovuto alla seguente riga di codice:
https://github.com/devcode-it/openstamanager/blob/22d71a40d2d5723dfec373d7e13eb11d9a0db26b/plugins/importFE/generate.php#L248

Potresti verificare che la query diretta sul database non presenti problemi?
```sql
SELECT
            co_documenti.id,
            CONCAT('Fattura num. ', co_documenti.numero_esterno, ' del ', DATE_FORMAT(co_documenti.data, '%d/%m/%Y')) AS descrizione
        FROM co_documenti
            INNER JOIN co_tipidocumento ON co_tipidocumento.id = co_documenti.idtipodocumento
        WHERE
            co_tipidocumento.dir = 'uscita' AND
            (co_documenti.data BETWEEN NOW() - INTERVAL 1 YEAR AND NOW()) AND
            co_documenti.idstatodocumento IN (SELECT id FROM co_statidocumento WHERE descrizione != 'Bozza') 
```

**Comment by maicol07** [comment]
La query funziona perfettamente. Nel mio file però c'è questa, che invece dà errori:

```sql
SELECT
           co_documenti.id,
           CONCAT('Fattura num. ', co_documenti.numero_esterno, ' del ', DATE_FORMAT(co_documenti.data, '%d/%m/%Y')) AS descrizione
       FROM co_documenti
           INNER JOIN co_tipidocumento ON co_tipidocumento.id = co_documenti.idtipodocumento
       ORDER BY co_documenti.data DESC
       WHERE
           co_tipidocumento.dir = 'uscita' AND
           (co_documenti.data BETWEEN NOW() - INTERVAL 2 YEAR AND NOW()) AND
           co_documenti.idstatodocumento IN (SELECT id FROM co_statidocumento WHERE descrizione != 'Bozza') AND
           co_documenti.idanagrafica = 5
```

Forse ho trovato l'errore: la query funziona se la clausola ORDER BY viene inserita dopo il where

**Comment by Dasc3er** [comment]
@maicol07 Credo tu abbia una versione vecchia o modificata del file: prova a sostituire l'intero file con i contenuti dell'ultimo commit.
